version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Enable QEMU
          command: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run:
          name: Build image
          command: docker build -t deviceplane/demo:$CIRCLE_SHA1 .
      - run:
          name: Docker login
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Deploy image
          command: docker push deviceplane/demo:$CIRCLE_SHA1

  deploy:
    docker:
      - image: deviceplane/cli:1.0.9
    steps:
      - checkout
      - run:
          name: Deploy to Device Plane
          command: deviceplane deploy deviceplane.yml

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
